### ISSUE TITLE
Manage registration ID changes

### ISSUE THREAD

**Issue by claustres** [kalisio/kNotify#2]
The GCM/FCM token can change due to token-rotation. For now we only register new device token when authenticating the user, we might do it anyway on registration ID changes.

**Comment by claustres** [comment]
We should add a hook on the user service with a specific create operation related to device only when the registration ID has changed and by passing the user creation by setting the hook result to the device.

**Comment by cnouguier** [comment]
registration ID changes is managed  using the new service 'devices'. See commit  3ff0e48
